### ISSUE TITLE
error in layout

### ISSUE THREAD

**Issue by amitmaheshwari** [evaletolab/karibou-api#49]
I am getting following error when trying to access home in the latest code. 

TypeError: C:\karibou\karibou-api-master\views\layout.jade:58
   56|         tr(colspan=4)
   57|           td: b Selections
 > 58|         each route in api.get
   59|             tr(style="background-color:#eee")
   60|               td: =route.path
   61|               td: =route.method

Cannot read property 'get' of undefined
   at eval (eval at <anonymous> (C:\karibou\karibou-api-master\node_modules\jade\lib\index.js:218:8), <anonymous>:445:18)
   at eval (eval at <anonymous> (C:\karibou\karibou-api-master\node_modules\jade\lib\index.js:218:8), <anonymous>:549:4)
   at eval (eval at <anonymous> (C:\karibou\karibou-api-master\node_modules\jade\lib\index.js:218:8), <anonymous>:1119:22)
   at res (C:\karibou\karibou-api-master\node_modules\jade\lib\index.js:219:38)
   at Object.exports.renderFile (C:\karibou\karibou-api-master\node_modules\jade\lib\index.js:380:38)
   at Object.exports.renderFile (C:\karibou\karibou-api-master\node_modules\jade\lib\index.js:370:21)
   at View.exports.__express [as engine] (C:\karibou\karibou-api-master\node_modules\jade\lib\index.js:417:11)
   at View.render (C:\karibou\karibou-api-master\node_modules\express\lib\view.js:126:8)
   at tryRender (C:\karibou\karibou-api-master\node_modules\express\lib\application.js:639:10)
   at EventEmitter.render (C:\karibou\karibou-api-master\node_modules\express\lib\application.js:591:3)
   at ServerResponse.render (C:\karibou\karibou-api-master\node_modules\express\lib\response.js:961:7)
   at C:\karibou\karibou-api-master\controllers\api.js:35:9
   at Layer.handle [as handle_request] (C:\karibou\karibou-api-master\node_modules\express\lib\router\layer.js:95:5)
   at next (C:\karibou\karibou-api-master\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (C:\karibou\karibou-api-master\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (C:\karibou\karibou-api-master\node_modules\express\lib\router\layer.js:95:5)
   at C:\karibou\karibou-api-master\node_modules\express\lib\router\index.js:277:22
   at Function.process_params (C:\karibou\karibou-api-master\node_modules\express\lib\router\index.js:330:12)
   at next (C:\karibou\karibou-api-master\node_modules\express\lib\router\index.js:271:10)
   at Layer.handle [as handle_request] (C:\karibou\karibou-api-master\node_modules\express\lib\router\layer.js:91:12)
   at trim_prefix (C:\karibou\karibou-api-master\node_modules\express\lib\router\index.js:312:13)
   at C:\karibou\karibou-api-master\node_modules\express\lib\router\index.js:280:7

**Comment by evaletolab** [comment]
there was an issue during the migration of node-express from 3 to 4. I fixed the crash but not the feature, the page will not display the correct values until I rewrite it. thks for submiting!
